### ISSUE TITLE
PreserveFormatting using docx-mailmerge

### ISSUE THREAD

**Issue by prayagvakharia** [Bouke/docx-mailmerge#34]
I need to add html content into MergeField but it will alwasy display as plain text. How can we Preserve Formatting for html text?

**Comment by Bouke** [comment]
This is not possible with this package. The text you provide will be injected inside some XML node as the node's text. In order to specify the markup, you would have to provide the correct Word XML markup and not the HTML markup. So you would have to come up with a transformation from HTML to Word XML. This package would have to be changed such that it inserts XML instead of text, in order to support formatted text.
